name: Build and test Java app

on:
  push:
    branches:
      [master, develop]

jobs:

  test-app:
    runs-on: linux-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start docker-compose
        run: |
          docker compose up -d

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Shutdown
        if: always()
        run: docker compose down -v --rmi all
